### PR TITLE
Add new template based on bootstrap 

### PR DESCRIPTION
**Pull request by briceflaceliere**
Add managing multiple templates and a new template based on bootstrap :

Image of bootstrap template

To use this template must be added an option `--template=bootstrap`.
I had to move the default template in the directory `templates/default/`.

I Develop primarily on PHP, so I can not respect the common rules node

### CODE REVIEW

**Comment by briceflaceliere** [comment]
up

**Comment by lukejpreston** [comment]
I have a demo.html file, could you make a second demo.html file which uses this bootstrap template as well and add a link to the index.html in the root directory. Then people can see what it will look like. Then I will merge this.

Sorry for the late reply

**Comment by lukejpreston** [comment]
also does this template have the filtering?

**Comment by briceflaceliere** [comment]
Hello,
I had not paid attention to the index.html nor to the demo
For now, I am not implemented all the filters available on your template. We can only filter by status (Sucess, Failure, Skipped ...).

**Comment by lukejpreston** [comment]
it should filter by test name, case name and by properties

you should be able to re-use the filtering functionality
you just need to think about how filtering will work in your new ui i.e. where will the input's go

**Comment by lukejpreston** [comment]
In terms of filtering you should be able to
1. hide/contract passing tests
2. hide/contract passing suites
3. hide/contract properties
4. filter suites
5. filter tests
6. filter properties
Each of the things above are independent of each other

This is important when someone has hundreds of tests and wishes to filter a smaller set into view
The current template has a separate menu for this which isn't important if you can think of better way to get these features

**Comment by lukejpreston** [comment]
I think I was only filtering out passed tests because I assumed error and failure are errors and just chucked skipped into this. If this is just a template I feel it should maintain this functionality or the other template should get this as well

But to be honest that wouldn't stop me merging. The filtering is a pretty important feature for junit-viewer

**Comment by briceflaceliere** [comment]
Thank you for your feedback, I will try to implement your remark when I have a moment.

**Comment by lukejpreston** [comment]
It looks good otherwise

**Comment by lukejpreston** [comment]
I am changing this project to use [xunit-viewer](https://lukejpreston.github.io/xunit-viewer/) soon. So I don't think this will be merged as it will be overwritten. Let me know what think of the new view. Some of it was inspired by this PR

**Comment by briceflaceliere** [comment]
The xunit-viewer interface is much clearer than the old.
My PR is no longer necessary. I will try to migrate our CI stack in the next few days, I will not hesitate to make you feedback.
This is a very good development.

**Comment by lukejpreston** [comment]
I would advise to hold off until this repo becomes `deprecated` which won't be very long.

**Comment by lukejpreston** [comment]
I did a bit more testing on xunit viewer and I am pretty confident it will work, so go ahead and try it out

**Pull request closed without merging**
